In [51]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from IPython.display import set_matplotlib_formats
import seaborn as sns

In [52]:
df = pd.read_csv('hynix_short.csv', index_col=0,parse_dates=[0], dayfirst=False,infer_datetime_format=True, encoding='cp949')

In [13]:
df.head()

,S금리대비,H금리대비,S등락,H등락,H등락분류,S종가,S등락률,H종가,H대비,H등락률,...,코스피변동,코스닥종가,코스닥시가,코스닥고가,코스닥저가,코스닥거래량,코스닥변동,SP종가,SP변동률,반도체수출금액지수
date,,,,,,,,,,,,,,,,,,,,,
2010-07-19,0,1,0,1,1,795000.0,-0.87,23700.0,200,0.85,...,-0.37,498.49,494.36,499.63,494.36,506010.0,-0.08,1071.25,0.88,88.15
2010-07-20,1,1,1,1,1,798000.0,0.38,23850.0,150,0.63,...,0.28,499.72,501.32,501.64,498.43,686750.0,0.25,1083.48,0.80,88.15
2010-07-21,1,0,1,0,-1,817000.0,2.38,23600.0,-250,-1.05,...,0.69,496.73,502.63,503.08,496.73,721150.0,-0.60,1069.59,1.74,88.15
2010-07-22,0,0,0,0,-1,808000.0,-1.10,22600.0,-1000,-4.24,...,-0.76,484.72,496.47,497.84,482.97,668020.0,-2.42,1093.67,-1.40,88.15
2010-07-23,1,1,1,1,1,811000.0,0.37,23250.0,650,2.88,...,1.30,483.69,490.17,490.65,480.66,532190.0,-0.21,1102.66,1.80,88.15

In [14]:
print(df.isna().sum())
print(df.shape)
print(list(df.columns))

S금리대비        0
H금리대비        0
S등락          0
H등락          0
H등락분류        0
S종가          0
S등락률         0
H종가          0
H대비          0
H등락률         0
H시가          0
H고가          0
H저가          0
H거래량         0
H거래대금        0
H시가총액        0
H상장주식수       0
원달러환율        0
유가종가         0
유가오픈         0
유가고가         0
유가저가         0
유가변동률        0
한국기준금리       0
미국기준금리       0
한미기준금리차이     0
정기예금환산       0
SOX종가        0
SOX변동률       0
BTC종가        0
BTC변동률       0
코스피종가        0
코스피고가        0
코스피저가        0
코스피거래량       0
코스피변동        0
코스닥종가        0
코스닥시가        0
코스닥고가        0
코스닥저가        0
코스닥거래량       0
코스닥변동        0
SP종가         0
SP변동률        0
반도체수출금액지수    0
dtype: int64
(2670, 45)
['S금리대비', 'H금리대비', 'S등락', 'H등락', 'H등락분류', 'S종가', 'S등락률', 'H종가', 'H대비', 'H등락률', 'H시가', 'H고가', 'H저가', 'H거래량', 'H거래대금', 'H시가총액', 'H상장주식수', '원달러환율', '유가종가', '유가오픈', '유가고가', '유가저가', '유가변동률', '한국기준금리', '미국기준금리', '한미기준금리차이', '정기예금환산', 'SOX종가', 'SOX변동률', 'BTC종가', 'BTC변동률', '코스피종가', '코스피고가', '코스피저가', '코스피거래량', '코스피변동', '코스닥종가', '코스닥시가', '코스닥고가', '코스닥저가', '코스닥거래량', '코스닥변동', 'SP종가', 'SP변동률', '반도체수출금액지수']

In [126]:
df = df.dropna(axis=0)

In [53]:
features = df[['S종가', 'H종가','원달러환율', '유가종가', '유가오픈', '유가고가', '유가저가', '유가변동률', '한국기준금리', '미국기준금리', '한미기준금리차이', '정기예금환산', 'SOX종가', 'SOX변동률', 'BTC종가', 'BTC변동률', '코스피종가', '코스피고가', '코스피저가', '코스피거래량', '코스피변동', '코스닥종가', '코스닥시가', '코스닥고가', '코스닥저가', '코스닥거래량', '코스닥변동', 'SP종가', 'SP변동률', '반도체수출금액지수']]
target = df['H금리대비']

features = StandardScaler().fit_transform(features)

In [54]:
random_seed = np.random.seed(2021)
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.1, random_state=random_seed)

In [55]:
lda = LinearDiscriminantAnalysis(n_components=1)

In [56]:
x_transform = lda.fit(x_train, y_train).transform(x_train)
y_predict = lda.fit(x_train, y_train).predict(x_test)

from sklearn import metrics
metrics.accuracy_score(y_test, y_predict)

0.6404494382022472

In [57]:
score = lda.score(x_train, y_train)
print("Score: ", score)

Score:  0.6741573033707865

In [30]:
lda.fit(features, target)
tr_lda = lda.transform(features)
tr_lda_component = pd.DataFrame(tr_lda,columns=['lda_component'])
tr_lda_component = pd.concat([tr_lda_component, target], axis=1)

In [31]:
tr_lda_component

                     lda_component  S금리대비
0                        -0.777341    NaN
1                        -0.066254    NaN
2                         0.887381    NaN
3                        -0.191559    NaN
4                         1.782518    NaN
...                            ...    ...
2021-05-10 00:00:00            NaN    1.0
2021-05-11 00:00:00            NaN    0.0
2021-05-12 00:00:00            NaN    0.0
2021-05-13 00:00:00            NaN    0.0
2021-05-14 00:00:00            NaN    1.0

[5340 rows x 2 columns]

In [32]:
markers=['^', 's', 'o']

#setosa의 target 값은 0, versicolor는 1, virginica는 2. 각 target 별로 다른 shape으로 scatter plot
for i, marker in enumerate(markers):
    x_axis_data = tr_lda_component[tr_lda_component['삼성등락']==i]['삼성등락']
    y_axis_data = tr_lda_component[tr_lda_component['삼성등락']==i]['lda_component']

    plt.scatter(x_axis_data, y_axis_data, marker=marker)

KeyError: '삼성등락'